export const SHOW_HEADER = 'SHOW_HEADER';
export const SELECT_USER_TO_MESSAGE = 'SELECT_USER_TO_MESSAGE';
export const WRITE_NEW_MESSAGE = 'WRITE_NEW_MESSAGE';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_USERS_PAGE = 'SET_CURRENT_USERS_PAGE';
export const SET_USERS_TOTAL_COUNT = 'SET_USERS_TOTAL_COUNT';